//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom9_WebsiteGiaySneaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaBrand { get; set; }
        public string TenBrand { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
