//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom9_WebsiteGiaySneaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.PhanQuyens = new HashSet<PhanQuyen>();
        }
    
        public int MaNV { get; set; }
        public string HoTenNV { get; set; }
        public Nullable<System.DateTime> NgaySinhNV { get; set; }
        public string GioiTinhNV { get; set; }
        public string DienThoaiNV { get; set; }
        public string TaiKhoanNV { get; set; }
        public string MatKhauNV { get; set; }
        public string EmailNV { get; set; }
        public string DiaChiNV { get; set; }
        public string ChucVuNC { get; set; }
    
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
    }
}
